# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_phishingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='phishingmodel',
            name='usid',
        ),
        migrations.DeleteModel(
            name='PhishingModel',
        ),
    ]
